// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_collection;

namespace api_collection.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20200722211451_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api_collection.Models.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FoodCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoodCategory = "Vegetarian"
                        },
                        new
                        {
                            Id = 2,
                            FoodCategory = "Chicken"
                        },
                        new
                        {
                            Id = 3,
                            FoodCategory = "Beef"
                        });
                });

            modelBuilder.Entity("api_collection.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RecipeImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 2,
                            FoodTypeId = 1,
                            RecipeImage = "",
                            RecipeName = "Matar Paneer"
                        },
                        new
                        {
                            RecipeId = 3,
                            FoodTypeId = 1,
                            RecipeImage = "",
                            RecipeName = "Black Bean Burger"
                        },
                        new
                        {
                            RecipeId = 4,
                            FoodTypeId = 1,
                            RecipeImage = "",
                            RecipeName = "Ratatouille"
                        },
                        new
                        {
                            RecipeId = 5,
                            FoodTypeId = 2,
                            RecipeImage = "",
                            RecipeName = "Chicken Enchiladas"
                        },
                        new
                        {
                            RecipeId = 6,
                            FoodTypeId = 2,
                            RecipeImage = "",
                            RecipeName = "Chicken Parmesean"
                        },
                        new
                        {
                            RecipeId = 7,
                            FoodTypeId = 2,
                            RecipeImage = "",
                            RecipeName = "Fried Chicken"
                        },
                        new
                        {
                            RecipeId = 8,
                            FoodTypeId = 3,
                            RecipeImage = "",
                            RecipeName = "Angus Burger"
                        },
                        new
                        {
                            RecipeId = 9,
                            FoodTypeId = 3,
                            RecipeImage = "",
                            RecipeName = "Steak"
                        },
                        new
                        {
                            RecipeId = 10,
                            FoodTypeId = 3,
                            RecipeImage = "",
                            RecipeName = "Pot Roast"
                        });
                });

            modelBuilder.Entity("api_collection.Models.Recipe", b =>
                {
                    b.HasOne("api_collection.Models.FoodType", "FoodType")
                        .WithMany("recipes")
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
